repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: leoniechrissi
  description: Praktikum
  author: Leonie Wehnert, Christina Parpoulas
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
