contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #leoniechrissi channel"
    url: https://nfcore.slack.com/channels/leoniechrissi
    about: Discussion about the nf-core/leoniechrissi pipeline
